HW3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HW3.Models
{
    public class FileModel
    {
        [Display(Name = "File Name" )]
        public string FileName { get; set; }
        
        
    }
}

HW3/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HW3.Models;

namespace HW3.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            //String array that will contain the file path of the fetched files using the "Directory.GetFiles()" function
            var path = Server.MapPath("~/Media/Documents");
            string[] folderPath = Directory.GetFiles(path); 
            List<FileModel> files = new List<FileModel>();
            //
            foreach (string filepath in folderPath)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filepath) });
            }
            //Returning the list to the view
            return View(files);
        }

        //Recieved file ("fileName") as a parameter sent to the view
        public FileResult DownloadFile(string fileName)
        {
            //To retrieve the full file path
            string path = Path.Combine(Server.MapPath("~/Media/Documents"), fileName);
            //To read the file data using the ReadAllBytes method passing the string path above
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            //Send and Return the downloaded file
            //System.Net.Mime.MediaTypeNames.Application.Octet to be able to handle any format of files that are downloaded
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Request.MapPath("~/Media/Documents/" + fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }


    }
}

HW3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HW3.Models;

namespace HW3.Controllers
{
    
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Documents = "checked";
            ViewBag.Image = "";
            ViewBag.Video = "";

            return View();
        }


        [HttpPost]
        //HttpPostedFileBase to get the file information uploaded by the user
        public ActionResult Index(HttpPostedFileBase Files, string fileType)
        {
            //If the folder doesn't exist on the user directory then it will be created
            string folderPath = Server.MapPath("~/Media/");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            //Check if the Files object is valid or not 
            if (Files != null && Files.ContentLength > 0)
            {
                //Get file name
                var fileName = Path.GetFileName(Files.FileName);
                //Upload all documents files under the document's folder if document is the checked radio button
                if (fileType == "Documents")
                {
                    ViewBag.Documents = "checked";

                    var path = Path.Combine(Server.MapPath("~/Media/Documents"), fileName);
                    //Get the file path together with the file name
                    var fullPath = Server.MapPath("~/Media/Documents") + Files.FileName;
                    if (System.IO.File.Exists(fullPath))
                    {
                        ViewBag.Message = "Same File already Exists";
                    }
                    else
                    {
                        Files.SaveAs(path);
                        ViewBag.Message = "File has been uploaded successfull";

                    }
                    ViewBag.Image = "";
                    ViewBag.Video = "";
                }

                //Upload all Images files under the image's folder if Image is the checked radio button
                if (fileType == "Image")
                {
                    ViewBag.Image = "checked";
                    var path = Path.Combine(Server.MapPath("~/Media/Image"), fileName);
                    var fullPath = Server.MapPath("~/Media/Image") + Files.FileName;
                    if (System.IO.File.Exists(fullPath))
                    {
                        ViewBag.Message = "Same File already Exists";
                    }
                    else
                    {
                        Files.SaveAs(path);
                        ViewBag.Message = "File has been uploaded successfull";

                    }
                    ViewBag.Documents = "";
                    ViewBag.Video = "";
                }

                //Upload all Videos files under the document's folder if Video is the checked radio button
                if (fileType == "Video")
                {
                    ViewBag.Video = "checked";
                    var path = Path.Combine(Server.MapPath("~/Media/Video"), fileName);
                    var fullPath = Server.MapPath("~/Media/Video") + Files.FileName;
                    if (System.IO.File.Exists(fullPath))
                    {
                        ViewBag.Message = "Same File already Exists";
                    }
                    else
                    {
                        Files.SaveAs(path);
                        ViewBag.ActionMessage = "File has been uploaded successfull";

                    }
                    ViewBag.Documents = "";
                    ViewBag.Image = "";
                }
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
           
            return View();
        }
    }
}

HW3/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HW3.Models;

namespace HW3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            string[] ImagePath = Directory.GetFiles(Server.MapPath("~/Media/Image"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filepath in ImagePath)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filepath) });
            }

            return View(files);
        }

        public FileResult DownloadFile(string fileName)
        {
            string path = Path.Combine(Server.MapPath("~/Media/Image"), fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Request.MapPath("~/Media/Image/" + fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }
    }
}

HW3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HW3.Models;

namespace HW3.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            string[] VideoPath = Directory.GetFiles(Server.MapPath("~/Media/Video"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filepath in VideoPath)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filepath) });
            }

            return View(files);
        }

        public FileResult DownloadFile(string fileName)
        {
            string path = Path.Combine(Server.MapPath("~/Media/Video"), fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Request.MapPath("~/Media/Video/" + fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }
    }
}

HW3/Views/File/Index.cshtml
@*@model IEnumerable<HW3.Models.FileModel>*@
@using HW3.Models
@model List<FileModel>


@{
    ViewBag.Title = "Index";
}


<div class="jumbotron">
    <header>
        <h3 class="text-center">Table Data</h3>
    </header>
    
    <br />
    <br />
    
    <table class="table table-responsive ">
        <thead class="bg-success">
            <tr>
                <th class="text-center">File Name</th>
                <th class="text-center">DOWNLOAD OPTION</th>
                <th class="text-center">DELETE OPTION</th>
            </tr>
        </thead>

        <tbody>
            @*To create the rows for the table*@
            @foreach (FileModel file in Model)
            {
                <tr>
                    <td>@file.FileName</td>
                    <td class="text-center btn btn-success">@Html.ActionLink("Download", "DownloadFile", new { fileName = file.FileName })</td>
                    <td class="text-center btn btn-danger">@Html.ActionLink("Delete", "DeleteFile", new { fileName = file.FileName })</td>
                </tr>
            }
        </tbody>
    </table>

</div>

HW3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}



<div class="container-fluid bg-info">
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <h3>Bio</h3>

            <p>
                Mfundo current a student at the University of Pretoria doing an Information Technology related course.<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
                ......................................<br />
            </p>
        </div>

        <div class="col-xs-12 col-md-6">
            <h3>Mfundo</h3>

            <img src="~/AboutImage/About.jpg" alt="image" height="300" width="350" />

            <br />
            <br />
        </div>
    </div>
</div>

HW3/Views/Home/Index.cshtml
@using HW3.Models


@{
    ViewBag.Title = "Home Page";
}

<div class="container bg-info">
    <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-6">
            <h3>Desciption</h3>

            <p>
                This system is a Media uploading system , which takes allows the user to upload files<br />
                from the user's computer and displays the uploaded files as a table.<br />
                The system have five views which all are different from each other.<br />
                The Home view is where the user selects the type of files that wants to be uploaded<br />
                The Files view is the one responsible for displaying all the uploaded files as a table with some addictional functionalities , like<br />
                download or delete files selected from or to the user's computer.<br />
                The Image view displays all the images uploaded using a fancy box.<br />
                The Videos view displays all the videos uploaded.<br />
                The About Me view is where the biography of the developer is displayed together with the image of the developer
            </p>

        </div>


        @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-xs-12 col-sm-6 col-md-6">
                <h3>Option Selection</h3>

                <input @ViewBag.Documents type="radio" name="FileType" value="Documents" /> Documents<br />
                <input @ViewBag.Image type="radio" name="FileType" value="Image" /> Image<br />
                <input @ViewBag.Video type="radio" name="FileType" value="Video" /> Video<br />
                <input type=file name="Files" /><br />
                <input type="submit" value="Submit" /><br />
                @ViewBag.Message

            </div>
        }


    </div>
</div>

HW3/Views/Image/Index.cshtml
@*@model IEnumerable<HW3.Models.FileModel>*@
@using HW3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
</head>


<body>
    <div class="jumbotron">
        <header class="text-center">
            <h3>Image Gallery</h3>
        </header>
    </div>

    <div>
        <section>
            <div>
                @foreach (FileModel file in Model)
                {
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <br />
                        <a class="gallery"
                           data-fancybox="gallery"
                           href="~/Media/Image/@file.FileName">
                            <img src="~/Media/Image/@file.FileName" width="300" height="200" />
                        </a>
                        <br />
                        <h5>@file.FileName</h5>
                        <p class="text-left btn btn-success">@Html.ActionLink("Download", "DownloadFile", new { fileName = file.FileName })</p>
                        <p class="text-center btn btn-danger">@Html.ActionLink("Delete", "DeleteFile", new { fileName = file.FileName })</p>
                        <br />
                    </div>
                }
            </div>
        </section>
    </div>

    <script>
        $(document).ready(function ($) {
            $('.gallery a').fancybox();
        });
    </script>
</body>

HW3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "#" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Files", "Index", "File")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                    <li>@Html.ActionLink("About Me", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HW3/Views/Video/Index.cshtml
@*@model IEnumerable<HW3.Models.FileModel>*@
@using HW3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
</head>

<body>
    <div class="jumbotron">
        <header class="text-center">
            <h3>Video Gallery</h3>
        </header>
    </div>

    <div>
        <section>
            <div>
                @foreach (FileModel file in Model)
                {
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <br />
                        <a class="gallery"
                           data-fancybox="gallery"
                           href="~/Media/Video/@file.FileName">
                            <video width="300" height="200">
                                <source src="~/Media/Video/@file.FileName" alt="video" type="video/mp4" />
                            </video>
                        </a>

                        <br />
                        <h5>@file.FileName</h5>
                        <p class="text-left btn btn-success">@Html.ActionLink("Download", "DownloadFile", new { fileName = file.FileName })</p>
                        <p class="text-center btn btn-danger">@Html.ActionLink("Delete", "DeleteFile", new { fileName = file.FileName })</p>
                        <br />
                    </div>
                }
            </div>
        </section>
    </div>

    <script>
        $(document).ready(function ($) {
            $('.gallery a').fancybox();
        });
    </script>
</body>